// Code generated by tygo. DO NOT EDIT.
// Source: backend/internal/models. Regenerate: cd backend && go run github.com/gzuidhof/tygo@v0.2.21 generate

//////////
// source: models.go

/**
 * TaskStatus represents the lifecycle state of a task
 */
export const TaskStatusPending = "pending";
export const TaskStatusQueued = "queued";
export const TaskStatusRunning = "running";
export const TaskStatusCompleted = "completed";
export const TaskStatusFailed = "failed";
export const TaskStatusRetrying = "retrying";
export const TaskStatusSkipped = "skipped";
export const TaskStatusDeadLetter = "dead_letter";
/**
 * TaskStatusCancelled is terminal: a task stopped because its execution
 * was cancelled, as opposed to one that failed on its own.
 */
export const TaskStatusCancelled = "cancelled";
export type TaskStatus = typeof TaskStatusPending | typeof TaskStatusQueued | typeof TaskStatusRunning | typeof TaskStatusCompleted | typeof TaskStatusFailed | typeof TaskStatusRetrying | typeof TaskStatusSkipped | typeof TaskStatusDeadLetter | typeof TaskStatusCancelled;
/**
 * WorkflowStatus represents the lifecycle state of a workflow execution
 */
export const WorkflowStatusPending = "pending";
export const WorkflowStatusRunning = "running";
export const WorkflowStatusCompleted = "completed";
export const WorkflowStatusFailed = "failed";
export const WorkflowStatusCancelled = "cancelled";
export const WorkflowStatusPaused = "paused";
export type WorkflowStatus = typeof WorkflowStatusPending | typeof WorkflowStatusRunning | typeof WorkflowStatusCompleted | typeof WorkflowStatusFailed | typeof WorkflowStatusCancelled | typeof WorkflowStatusPaused;
/**
 * TriggerRule decides when a task runs, from how its dependencies ended.
 */
/**
 * TriggerRuleAllSuccess, the default, runs once every dependency
 * completed, and skips the task if any dependency failed or was skipped.
 */
export const TriggerRuleAllSuccess = "all_success";
/**
 * TriggerRuleAllDone runs once every dependency has finished, however.
 */
export const TriggerRuleAllDone = "all_done";
/**
 * TriggerRuleOneFailed runs once any dependency failed, and skips the task
 * if every dependency finished without failing.
 */
export const TriggerRuleOneFailed = "one_failed";
export type TriggerRule = typeof TriggerRuleAllSuccess | typeof TriggerRuleAllDone | typeof TriggerRuleOneFailed;
/**
 * ArtifactRef describes a file artifact stored in MinIO.
 * Path is always relative to the task's artifact directory.
 * 	MinIO key: artifacts/{workflow_exec_id}/{task_def_id}/{Path}
 */
export interface ArtifactRef {
	path: string; // e.g. "output.json" or "results/data.csv"
	description?: string; // human-readable label shown in UI
}
/**
 * ContainerSpec holds security and resource settings for the isolated container.
 */
export interface ContainerSpec {
	image: string; // e.g. "python:3.12-slim"
	memory_mb?: number /* int64 */; // hard memory limit (default 256)
	cpu_millis?: number /* int64 */; // CPU quota in milli-CPUs (default 500)
	env?: { [key: string]: string}; // extra env vars injected into container
	work_dir?: string; // working directory inside container (default /workspace)
}
/**
 * RetryPolicy defines retry behavior for tasks
 */
export interface RetryPolicy {
	max_retries: number /* int */;
	initial_delay: number /* nanoseconds */;
	max_delay: number /* nanoseconds */;
	backoff_multiplier: number /* float64 */;
	jitter: boolean;
}
/**
 * TaskDefinition defines a single task within a workflow DAG
 * ArtifactsIn  — paths produced by dependency tasks that this task needs.
 * 	The worker downloads these from MinIO and places them in the
 * 	container's /workspace before starting execution.
 * ArtifactsOut — paths this task will produce inside /workspace.
 * 	The worker uploads these to MinIO after the container exits.
 * Container    — Docker image and resource limits for the isolated executor.
 * 	Optional for code task types (data_transform, generic, ml_inference),
 * 	which always run in a container; nil applies the defaults. For the
 * 	other types, nil runs the task in-process.
 */
export interface TaskDefinition {
	id: string;
	name: string;
	type: string;
	dependencies: string[];
	config: { [key: string]: any};
	retry_policy?: RetryPolicy;
	timeout: number /* nanoseconds */;
	max_parallel?: number /* int */;
	metadata?: { [key: string]: string};
	container?: ContainerSpec;
	artifacts_in?: ArtifactRef[];
	artifacts_out?: ArtifactRef[];
	trigger_rule?: TriggerRule;
	/**
	 * When is a template that must render to "true" for the task to run, as
	 * in {{ eq .payload.env "prod" }}; anything else skips it. It sees what
	 * config templates see and is checked once TriggerRule is met.
	 */
	when?: string;
}
/**
 * WorkflowDefinition is the DAG specification
 */
export interface WorkflowDefinition {
	id: string;
	name: string;
	description: string;
	version: string;
	tasks: TaskDefinition[];
	global_retry?: RetryPolicy;
	max_parallel: number /* int */;
	tags?: { [key: string]: string};
	/**
	 * Schedule is a cron expression (five fields or a descriptor, UTC) that
	 * starts a run each time it fires; empty means none.
	 */
	schedule?: string;
	/**
	 * NextRunAt is when Schedule next fires. The server sets it; input is ignored.
	 */
	next_run_at?: string /* RFC3339 */;
	alerts?: WorkflowAlerts;
	created_at: string /* RFC3339 */;
	updated_at: string /* RFC3339 */;
}
/**
 * WorkflowAlerts names where a finished run's outcome is posted. A cancelled
 * run posts nothing: someone chose to stop it.
 */
export interface WorkflowAlerts {
	on_success?: AlertTarget;
	on_failure?: AlertTarget;
}
/**
 * AlertTarget is an http or https URL that receives the alert as a JSON POST.
 */
export interface AlertTarget {
	url: string;
}
/**
 * WorkflowRevision is one saved state of a workflow definition. Revisions
 * count up from 1 per workflow and are never changed.
 */
export interface WorkflowRevision {
	revision: number /* int */;
	created_at: string /* RFC3339 */;
}
/**
 * ResolvedArtifact is an ArtifactRef with its fully-qualified MinIO key resolved.
 */
export interface ResolvedArtifact {
	path: string; // relative path inside container workspace
	minio_key: string; // full MinIO object key
	size: number /* int64 */; // bytes, set after upload
}
/**
 * WorkflowExecution is a runtime instance of a WorkflowDefinition
 */
export interface WorkflowExecution {
	id: string;
	workflow_id: string;
	workflow_name: string;
	status: WorkflowStatus;
	tasks: TaskExecution[];
	started_at?: string /* RFC3339 */;
	completed_at?: string /* RFC3339 */;
	trigger_payload?: { [key: string]: any};
	error?: string;
	metadata?: { [key: string]: string};
	created_at: string /* RFC3339 */;
	updated_at: string /* RFC3339 */;
}
/**
 * TaskExecution tracks the runtime state of a single task
 */
export interface TaskExecution {
	id: string;
	workflow_exec_id: string;
	task_definition_id: string;
	task_name: string;
	task_type: string;
	status: TaskStatus;
	retry_count: number /* int */;
	max_retries: number /* int */;
	worker_id?: string;
	queued_at?: string /* RFC3339 */;
	started_at?: string /* RFC3339 */;
	completed_at?: string /* RFC3339 */;
	next_retry_at?: string /* RFC3339 */;
	output?: unknown;
	error?: string;
	logs?: LogEntry[];
	metadata?: { [key: string]: string};
	duration?: number /* nanoseconds */;
	created_at: string /* RFC3339 */;
	updated_at: string /* RFC3339 */;
	artifacts_in?: ResolvedArtifact[];
	artifacts_out?: ResolvedArtifact[];
}
/**
 * LogEntry represents a single log line from a task execution
 */
export interface LogEntry {
	timestamp: string /* RFC3339 */;
	level: 'info' | 'warn' | 'error' | 'debug';
	/**
	 * Attempt is the retry_count that produced the entry: the row's logs span every attempt.
	 */
	attempt: number /* int */;
	message: string;
	fields?: { [key: string]: any};
}
/**
 * TaskMessage is what gets enqueued in Redis for workers
 */
export interface TaskMessage {
	task_exec_id: string;
	workflow_exec_id: string;
	workflow_id: string;
	task_def_id: string;
	task_name: string;
	task_type: string;
	config: { [key: string]: any};
	retry_count: number /* int */;
	max_retries: number /* int */;
	timeout: number /* nanoseconds */;
	enqueued_at: string /* RFC3339 */;
	container?: ContainerSpec;
	artifacts_in?: ResolvedArtifact[];
	artifacts_out?: ArtifactRef[];
	/**
	 * TemplateData is what the worker renders Config's templates against: the
	 * trigger payload and the dependencies' outputs. Set only when Config has
	 * templates.
	 */
	template_data?: { [key: string]: any};
}
/**
 * TaskResult is what workers publish back
 */
export interface TaskResult {
	task_exec_id: string;
	workflow_exec_id: string;
	worker_id: string;
	/**
	 * RetryCount is the attempt the worker ran. It is a pointer because
	 * results published before the field existed omit it; see Attempt.
	 */
	retry_count?: number /* int */;
	success: boolean;
	output?: unknown;
	error?: string;
	logs?: LogEntry[];
	started_at: string /* RFC3339 */;
	completed_at: string /* RFC3339 */;
	artifacts_out?: ResolvedArtifact[];
}
/**
 * WebSocketEvent is sent to connected UI clients
 */
export interface WebSocketEvent {
	type: string;
	payload: any;
}
export const WSEventWorkflowStarted = "workflow.started";
export const WSEventWorkflowCompleted = "workflow.completed";
export const WSEventWorkflowFailed = "workflow.failed";
export const WSEventWorkflowCancelled = "workflow.cancelled";
export const WSEventTaskQueued = "task.queued";
export const WSEventTaskStarted = "task.started";
export const WSEventTaskCompleted = "task.completed";
export const WSEventTaskFailed = "task.failed";
export const WSEventTaskRetrying = "task.retrying";
export const WSEventTaskSkipped = "task.skipped";
export const WSEventTaskLog = "task.log";
export const WSEventMetrics = "metrics.update";
export type WSEvent = typeof WSEventWorkflowStarted | typeof WSEventWorkflowCompleted | typeof WSEventWorkflowFailed | typeof WSEventWorkflowCancelled | typeof WSEventTaskQueued | typeof WSEventTaskStarted | typeof WSEventTaskCompleted | typeof WSEventTaskFailed | typeof WSEventTaskRetrying | typeof WSEventTaskSkipped | typeof WSEventTaskLog | typeof WSEventMetrics;
