import type { WorkflowDefinition } from '../types'

/**
 * Pre-built workflow templates the user can load into the DAG editor.
 * Each template is a complete WorkflowDefinition (minus id/timestamps).
 */
export const WORKFLOW_TEMPLATES: Array<
	Omit<WorkflowDefinition, 'id' | 'created_at' | 'updated_at'>
> = [
	// ── ETL Pipeline ────────────────────────────────────────
	{
		name: 'ETL Pipeline',
		description: 'Extract → validate → transform → load data warehouse pattern',
		version: '1.0.0',
		max_parallel: 6,
		tags: { category: 'data', domain: 'etl' },
		tasks: [
			{
				id: 'ingest-raw',
				name: 'Ingest Raw Data',
				type: 'database_query',
				dependencies: [],
				config: {
					connection_string: 'postgres://user:pass@host:5432/db',
					query: 'SELECT * FROM raw_events',
					max_rows: 100000,
				},
				retry_policy: {
					max_retries: 3,
					initial_delay: 2e9,
					max_delay: 60e9,
					backoff_multiplier: 2,
					jitter: true,
				},
				timeout: 300e9,
			},
			{
				id: 'validate-schema',
				name: 'Validate Schema',
				type: 'data_transform',
				dependencies: ['ingest-raw'],
				config: { script: 'echo validating against events_v2' },
				retry_policy: {
					max_retries: 2,
					initial_delay: 1e9,
					max_delay: 30e9,
					backoff_multiplier: 2,
					jitter: true,
				},
				timeout: 120e9,
			},
			{
				id: 'clean-dedupe',
				name: 'Clean & Deduplicate',
				type: 'data_transform',
				dependencies: ['validate-schema'],
				config: { script: 'echo deduplicating on event_id' },
				timeout: 180e9,
			},
			{
				id: 'enrich-geo',
				name: 'Geo Enrichment',
				type: 'http_request',
				dependencies: ['validate-schema'],
				config: { url: 'https://api.geo.internal/enrich', method: 'POST' },
				retry_policy: {
					max_retries: 5,
					initial_delay: 1e9,
					max_delay: 120e9,
					backoff_multiplier: 2,
					jitter: true,
				},
				timeout: 240e9,
			},
			{
				id: 'apply-transform',
				name: 'Apply Business Rules',
				type: 'data_transform',
				dependencies: ['clean-dedupe', 'enrich-geo'],
				config: { script: 'echo applying business rules v4' },
				timeout: 300e9,
			},
			{
				id: 'load-warehouse',
				name: 'Load to Warehouse',
				type: 'database_query',
				dependencies: ['apply-transform'],
				config: {
					connection_string: 'postgres://user:pass@host:5432/db',
					query: 'INSERT INTO analytics.events SELECT * FROM staging_events',
				},
				retry_policy: {
					max_retries: 3,
					initial_delay: 5e9,
					max_delay: 300e9,
					backoff_multiplier: 2,
					jitter: true,
				},
				timeout: 600e9,
			},
			{
				id: 'notify-success',
				name: 'Send Completion Report',
				type: 'notification',
				dependencies: ['apply-transform'],
				config: {
					notify_type: 'slack',
					channel: 'https://hooks.slack.com/services/REPLACE_ME',
					message: 'ETL pipeline complete',
				},
				timeout: 30e9,
			},
		],
	},

	// ── ML Training Pipeline ────────────────────────────────
	{
		name: 'ML Training Pipeline',
		description: 'End-to-end model training: fetch → preprocess → train → evaluate → deploy',
		version: '1.0.0',
		max_parallel: 4,
		tags: { category: 'ml', domain: 'training' },
		tasks: [
			{
				id: 'fetch-dataset',
				name: 'Fetch Dataset',
				type: 'http_request',
				dependencies: [],
				config: { url: 'https://data.internal/datasets/latest', method: 'GET' },
				timeout: 600e9,
			},
			{
				id: 'preprocess',
				name: 'Feature Engineering',
				type: 'data_transform',
				dependencies: ['fetch-dataset'],
				config: { script: 'echo normalising features' },
				timeout: 900e9,
			},
			{
				id: 'train-val-split',
				name: 'Train / Val Split',
				type: 'generic',
				dependencies: ['preprocess'],
				config: { script: 'echo splitting 80/20' },
				timeout: 120e9,
			},
			{
				id: 'train-model',
				name: 'Train Model',
				type: 'ml_inference',
				dependencies: ['train-val-split'],
				config: { model_name: 'train-xgboost', batch_size: 100 },
				retry_policy: {
					max_retries: 2,
					initial_delay: 30e9,
					max_delay: 300e9,
					backoff_multiplier: 2,
					jitter: false,
				},
				timeout: 3600e9,
			},
			{
				id: 'evaluate',
				name: 'Evaluate on Val Set',
				type: 'ml_inference',
				dependencies: ['train-model'],
				config: { model_name: 'evaluate-model', output_path: '/workspace/metrics.json' },
				timeout: 600e9,
			},
			{
				id: 'register-model',
				name: 'Register in Model Registry',
				type: 'http_request',
				dependencies: ['evaluate'],
				config: {
					url: 'https://mlflow.internal/api/2.0/mlflow/model-versions/create',
					method: 'POST',
					body: '{"name": "model"}',
				},
				timeout: 120e9,
			},
			{
				id: 'deploy-canary',
				name: 'Deploy Canary (5%)',
				type: 'http_request',
				dependencies: ['register-model'],
				config: {
					url: 'https://deploy.internal/canary',
					method: 'POST',
					body: '{"traffic_split": 5}',
				},
				timeout: 300e9,
			},
			{
				id: 'setup-monitoring',
				name: 'Configure Drift Monitoring',
				type: 'generic',
				dependencies: ['deploy-canary'],
				config: { script: 'echo configuring drift monitoring' },
				timeout: 60e9,
			},
		],
	},

	// ── Microservice Deploy ─────────────────────────────────
	{
		name: 'Microservice Deploy',
		description: 'CI/CD pipeline: build → test → scan → push → deploy → smoke test',
		version: '1.0.0',
		max_parallel: 8,
		tags: { category: 'devops', domain: 'cicd' },
		tasks: [
			{
				id: 'checkout',
				name: 'Checkout & Dependencies',
				type: 'generic',
				dependencies: [],
				config: { script: 'git checkout main && npm ci' },
				timeout: 120e9,
			},
			{
				id: 'lint',
				name: 'Lint & Type Check',
				type: 'generic',
				dependencies: ['checkout'],
				config: {},
				timeout: 60e9,
			},
			{
				id: 'unit-tests',
				name: 'Unit Tests',
				type: 'generic',
				dependencies: ['checkout'],
				config: { script: 'npm test -- --coverage' },
				timeout: 180e9,
			},
			{
				id: 'build-image',
				name: 'Build Docker Image',
				type: 'generic',
				dependencies: ['lint', 'unit-tests'],
				config: { script: 'docker build -t app .' },
				timeout: 300e9,
			},
			{
				id: 'security-scan',
				name: 'Security Scan (Trivy)',
				type: 'http_request',
				dependencies: ['build-image'],
				config: { url: 'https://scanner.internal/scan', method: 'POST' },
				timeout: 180e9,
			},
			{
				id: 'push-registry',
				name: 'Push to Registry',
				type: 'http_request',
				dependencies: ['security-scan'],
				config: { url: 'https://registry.internal/push', method: 'POST' },
				timeout: 120e9,
			},
			{
				id: 'deploy-staging',
				name: 'Deploy to Staging',
				type: 'http_request',
				dependencies: ['push-registry'],
				config: { url: 'https://deploy.internal/staging', method: 'POST' },
				timeout: 300e9,
			},
			{
				id: 'integration-tests',
				name: 'Integration Tests',
				type: 'generic',
				dependencies: ['deploy-staging'],
				config: { script: 'echo running smoke suite' },
				timeout: 600e9,
			},
			{
				id: 'deploy-prod',
				name: 'Deploy to Production',
				type: 'http_request',
				dependencies: ['integration-tests'],
				config: { url: 'https://deploy.internal/production', method: 'POST' },
				timeout: 600e9,
			},
			{
				id: 'notify-team',
				name: 'Notify Engineering Team',
				type: 'notification',
				dependencies: ['deploy-prod'],
				config: {
					notify_type: 'slack',
					channel: 'https://hooks.slack.com/services/REPLACE_ME',
					message: 'Deployed to production',
				},
				timeout: 30e9,
			},
		],
	},

	// ── Daily Reporting ─────────────────────────────────────
	{
		name: 'Daily Business Report',
		description: 'Aggregate KPIs → generate charts → email stakeholders',
		version: '1.0.0',
		max_parallel: 5,
		tags: { category: 'reporting', schedule: 'daily' },
		tasks: [
			{
				id: 'fetch-revenue',
				name: 'Fetch Revenue Data',
				type: 'database_query',
				dependencies: [],
				config: { query: 'SELECT * FROM revenue_daily WHERE date = current_date' },
				timeout: 120e9,
			},
			{
				id: 'fetch-users',
				name: 'Fetch User Metrics',
				type: 'database_query',
				dependencies: [],
				config: { query: 'SELECT * FROM user_activity_daily WHERE date = current_date' },
				timeout: 120e9,
			},
			{
				id: 'fetch-infra',
				name: 'Fetch Infra Costs',
				type: 'http_request',
				dependencies: [],
				config: { url: 'https://api.aws.internal/costs/today' },
				timeout: 60e9,
			},
			{
				id: 'aggregate-kpis',
				name: 'Aggregate KPIs',
				type: 'data_transform',
				dependencies: ['fetch-revenue', 'fetch-users', 'fetch-infra'],
				config: { script: 'echo summarising' },
				timeout: 60e9,
			},
			{
				id: 'generate-charts',
				name: 'Generate Charts',
				type: 'ml_inference',
				dependencies: ['aggregate-kpis'],
				config: { model_name: 'render-charts', output_path: '/workspace/charts.png' },
				timeout: 120e9,
			},
			{
				id: 'compile-report',
				name: 'Compile PDF Report',
				type: 'data_transform',
				dependencies: ['generate-charts'],
				config: { script: 'echo building executive summary' },
				timeout: 60e9,
			},
			{
				id: 'email-stakeholders',
				name: 'Email Stakeholders',
				type: 'notification',
				dependencies: ['compile-report'],
				config: {
					notify_type: 'email',
					channel: 'ceo@acme.com',
					message: 'Daily KPI report is ready',
				},
				timeout: 30e9,
			},
		],
	},
]
