import type { WorkflowDefinition } from '../types'

/**
 * Pre-built workflow templates the user can load into the DAG editor.
 * Each template is a complete WorkflowDefinition (minus id/timestamps).
 */
export const WORKFLOW_TEMPLATES: Array<
	Omit<WorkflowDefinition, 'id' | 'created_at' | 'updated_at'>
> = [
	// ── ETL Pipeline ────────────────────────────────────────
	{
		name: 'ETL Pipeline',
		description: 'Extract → validate → transform → load data warehouse pattern',
		version: '1.0.0',
		max_parallel: 6,
		tags: { category: 'data', domain: 'etl' },
		tasks: [
			{
				id: 'ingest-raw',
				name: 'Ingest Raw Data',
				type: 'database_query',
				dependencies: [],
				config: { table: 'raw_events', limit: 100000 },
				retry_policy: {
					max_retries: 3,
					initial_delay: 2e9,
					max_delay: 60e9,
					backoff_multiplier: 2,
					jitter: true,
				},
				timeout: 300e9,
			},
			{
				id: 'validate-schema',
				name: 'Validate Schema',
				type: 'data_transform',
				dependencies: ['ingest-raw'],
				config: { schema: 'events_v2', strict: true },
				retry_policy: {
					max_retries: 2,
					initial_delay: 1e9,
					max_delay: 30e9,
					backoff_multiplier: 2,
					jitter: true,
				},
				timeout: 120e9,
			},
			{
				id: 'clean-dedupe',
				name: 'Clean & Deduplicate',
				type: 'data_transform',
				dependencies: ['validate-schema'],
				config: { dedup_key: 'event_id', drop_nulls: true },
				timeout: 180e9,
			},
			{
				id: 'enrich-geo',
				name: 'Geo Enrichment',
				type: 'http_request',
				dependencies: ['validate-schema'],
				config: { url: 'https://api.geo.internal/enrich', method: 'POST' },
				retry_policy: {
					max_retries: 5,
					initial_delay: 1e9,
					max_delay: 120e9,
					backoff_multiplier: 2,
					jitter: true,
				},
				timeout: 240e9,
			},
			{
				id: 'apply-transform',
				name: 'Apply Business Rules',
				type: 'data_transform',
				dependencies: ['clean-dedupe', 'enrich-geo'],
				config: { rules_version: 'v4' },
				timeout: 300e9,
			},
			{
				id: 'load-warehouse',
				name: 'Load to Warehouse',
				type: 'database_query',
				dependencies: ['apply-transform'],
				config: { target: 'analytics.events', mode: 'upsert' },
				retry_policy: {
					max_retries: 3,
					initial_delay: 5e9,
					max_delay: 300e9,
					backoff_multiplier: 2,
					jitter: true,
				},
				timeout: 600e9,
			},
			{
				id: 'notify-success',
				name: 'Send Completion Report',
				type: 'notification',
				dependencies: ['apply-transform'],
				config: { channel: '#data-team', template: 'etl_complete' },
				timeout: 30e9,
			},
		],
	},

	// ── ML Training Pipeline ────────────────────────────────
	{
		name: 'ML Training Pipeline',
		description: 'End-to-end model training: fetch → preprocess → train → evaluate → deploy',
		version: '1.0.0',
		max_parallel: 4,
		tags: { category: 'ml', domain: 'training' },
		tasks: [
			{
				id: 'fetch-dataset',
				name: 'Fetch Dataset',
				type: 'http_request',
				dependencies: [],
				config: { url: 'https://data.internal/datasets/latest', format: 'parquet' },
				timeout: 600e9,
			},
			{
				id: 'preprocess',
				name: 'Feature Engineering',
				type: 'data_transform',
				dependencies: ['fetch-dataset'],
				config: { normalize: true, fill_strategy: 'median' },
				timeout: 900e9,
			},
			{
				id: 'train-val-split',
				name: 'Train / Val Split',
				type: 'generic',
				dependencies: ['preprocess'],
				config: { train_ratio: 0.8, seed: 42, stratified: true },
				timeout: 120e9,
			},
			{
				id: 'train-model',
				name: 'Train Model',
				type: 'ml_inference',
				dependencies: ['train-val-split'],
				config: { model: 'xgboost', epochs: 100, early_stopping: 10 },
				retry_policy: {
					max_retries: 2,
					initial_delay: 30e9,
					max_delay: 300e9,
					backoff_multiplier: 2,
					jitter: false,
				},
				timeout: 3600e9,
			},
			{
				id: 'evaluate',
				name: 'Evaluate on Val Set',
				type: 'ml_inference',
				dependencies: ['train-model'],
				config: { metrics: ['auc', 'f1', 'precision', 'recall'] },
				timeout: 600e9,
			},
			{
				id: 'register-model',
				name: 'Register in Model Registry',
				type: 'http_request',
				dependencies: ['evaluate'],
				config: { registry: 'mlflow', stage: 'staging' },
				timeout: 120e9,
			},
			{
				id: 'deploy-canary',
				name: 'Deploy Canary (5%)',
				type: 'http_request',
				dependencies: ['register-model'],
				config: { traffic_split: 5, env: 'production' },
				timeout: 300e9,
			},
			{
				id: 'setup-monitoring',
				name: 'Configure Drift Monitoring',
				type: 'generic',
				dependencies: ['deploy-canary'],
				config: { alert_threshold: 0.05, window: '1h' },
				timeout: 60e9,
			},
		],
	},

	// ── Microservice Deploy ─────────────────────────────────
	{
		name: 'Microservice Deploy',
		description: 'CI/CD pipeline: build → test → scan → push → deploy → smoke test',
		version: '1.0.0',
		max_parallel: 8,
		tags: { category: 'devops', domain: 'cicd' },
		tasks: [
			{
				id: 'checkout',
				name: 'Checkout & Dependencies',
				type: 'generic',
				dependencies: [],
				config: { ref: 'main', install: true },
				timeout: 120e9,
			},
			{
				id: 'lint',
				name: 'Lint & Type Check',
				type: 'generic',
				dependencies: ['checkout'],
				config: {},
				timeout: 60e9,
			},
			{
				id: 'unit-tests',
				name: 'Unit Tests',
				type: 'generic',
				dependencies: ['checkout'],
				config: { coverage_threshold: 80 },
				timeout: 180e9,
			},
			{
				id: 'build-image',
				name: 'Build Docker Image',
				type: 'generic',
				dependencies: ['lint', 'unit-tests'],
				config: { dockerfile: 'Dockerfile', platform: 'linux/amd64' },
				timeout: 300e9,
			},
			{
				id: 'security-scan',
				name: 'Security Scan (Trivy)',
				type: 'http_request',
				dependencies: ['build-image'],
				config: { scanner: 'trivy', severity: 'HIGH,CRITICAL' },
				timeout: 180e9,
			},
			{
				id: 'push-registry',
				name: 'Push to Registry',
				type: 'http_request',
				dependencies: ['security-scan'],
				config: { registry: 'ghcr.io', tag_latest: true },
				timeout: 120e9,
			},
			{
				id: 'deploy-staging',
				name: 'Deploy to Staging',
				type: 'http_request',
				dependencies: ['push-registry'],
				config: { env: 'staging', strategy: 'rolling', max_surge: 1 },
				timeout: 300e9,
			},
			{
				id: 'integration-tests',
				name: 'Integration Tests',
				type: 'generic',
				dependencies: ['deploy-staging'],
				config: { suite: 'smoke', parallel: 4 },
				timeout: 600e9,
			},
			{
				id: 'deploy-prod',
				name: 'Deploy to Production',
				type: 'http_request',
				dependencies: ['integration-tests'],
				config: { env: 'production', strategy: 'blue-green' },
				timeout: 600e9,
			},
			{
				id: 'notify-team',
				name: 'Notify Engineering Team',
				type: 'notification',
				dependencies: ['deploy-prod'],
				config: { channel: '#deployments', include_diff: true },
				timeout: 30e9,
			},
		],
	},

	// ── Daily Reporting ─────────────────────────────────────
	{
		name: 'Daily Business Report',
		description: 'Aggregate KPIs → generate charts → email stakeholders',
		version: '1.0.0',
		max_parallel: 5,
		tags: { category: 'reporting', schedule: 'daily' },
		tasks: [
			{
				id: 'fetch-revenue',
				name: 'Fetch Revenue Data',
				type: 'database_query',
				dependencies: [],
				config: { query: 'SELECT * FROM revenue_daily WHERE date = current_date' },
				timeout: 120e9,
			},
			{
				id: 'fetch-users',
				name: 'Fetch User Metrics',
				type: 'database_query',
				dependencies: [],
				config: { query: 'SELECT * FROM user_activity_daily WHERE date = current_date' },
				timeout: 120e9,
			},
			{
				id: 'fetch-infra',
				name: 'Fetch Infra Costs',
				type: 'http_request',
				dependencies: [],
				config: { url: 'https://api.aws.internal/costs/today' },
				timeout: 60e9,
			},
			{
				id: 'aggregate-kpis',
				name: 'Aggregate KPIs',
				type: 'data_transform',
				dependencies: ['fetch-revenue', 'fetch-users', 'fetch-infra'],
				config: { output_format: 'json' },
				timeout: 60e9,
			},
			{
				id: 'generate-charts',
				name: 'Generate Charts',
				type: 'ml_inference',
				dependencies: ['aggregate-kpis'],
				config: { renderer: 'matplotlib', format: 'png', dpi: 150 },
				timeout: 120e9,
			},
			{
				id: 'compile-report',
				name: 'Compile PDF Report',
				type: 'data_transform',
				dependencies: ['generate-charts'],
				config: { template: 'executive_summary_v2', pages: 8 },
				timeout: 60e9,
			},
			{
				id: 'email-stakeholders',
				name: 'Email Stakeholders',
				type: 'notification',
				dependencies: ['compile-report'],
				config: { recipients: ['ceo@acme.com', 'cto@acme.com'], subject: 'Daily KPI Report' },
				timeout: 30e9,
			},
		],
	},
]
